Check for literal value in signature with .return(-rw)
https://github.com/rakudo/rakudo/issues/6003 pointed out that all
return typechecks were bypassed if a literal return value was
specified in the signature **and** .return or .return-rw were used.

  $ raku -e 'sub a(--> 42) { "foo".return }; dd a'
  foo

This problem does not occur when using the return(-rw) sub, because
that causes a compilation error:

  $ raku -e 'sub a(--> 42) { return "foo" }; dd a'
  ===SORRY!=== Error while compiling -e
  No return arguments allowed when return value 42 is already
  specified in the signature

But since methods are late bound, there is no way to reliably spot
this during compilation.

This commit adds a helper subroutine that introspects the call chain
for the first Routine, then checks its "returns" signature, and if
that indicates something defined, throws an execution error with as
much information as possible.

From a performance point of view, this puts a *large* overhead on
the value.return idiom.  So maybe we should consider deprecating
that idiom if this gets merged.