Change all TWEAK methods to submethods
To prevent them from being called more than once if a subclass is
instantiated.

A special note about IO::Pipe: $.nl-out.list needed to be replaced
with self.nl-out.list because the virtual $.nl-out attribute call
caused a compilation error: X::Syntax::VirtualCall during setting
building.  This error actually feels wrong for method TWEAK as at
that time the underlying invocant is already fully built (espcially
with regards to attributes in base classes).

Found while investigating RakuAST approaches to object building.